spring.application.name=studio-snaps

spring.datasource.url=jdbc:mysql://localhost:3306/studiohub
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=100MB

# AWS S3
studio.aws.region=${AWS_REGION:ap-south-1}
studio.aws.s3.bucket=${STUDIO_S3_BUCKET:studio-snaps-photos}

# THIS IS THE KEY LINE
studio.storage.type=s3

server.port=8081